### PR TITLE
Simple nested structs tests

### PR DESCRIPTION
**Pull request by liuzikai**
Hi,

I am not sure whether there are already tests of GEP that walk into nested structs. Here are a few simple ones :)

Thanks,
Zikai

### CODE REVIEW

**Comment by nicdard** [comment]
Hi, thank you for the tests!

Just one thing: I see one commit (the one from october 21) that has already been merged, can you please remove it together with the merge commit? After doing this, you can also squash the two commits with the changes (also please use capital letter after colon in the commit message), or leave them as they are and I will squash them before merging.

**Review by nicdard — CHANGES_REQUESTED** [review]
LGTM, the only minor thing is the issue with old commits

**Comment by liuzikai** [comment]
> Hi, thank you for the tests!
> 
> Just one thing: I see one commit (the one from october 21) that has already been merged, can you please remove it together with the merge commit? After doing this, you can also squash the two commits with the changes (also please use capital letter after colon in the commit message), or leave them as they are and I will squash them before merging.

I also wonder why there is the dangling commit. Maybe I didn't do it right when merge the upstream. 

It's done now (also merge the fix commit).

**Comment by nicdard** [comment]
> > Hi, thank you for the tests!
> > Just one thing: I see one commit (the one from october 21) that has already been merged, can you please remove it together with the merge commit? After doing this, you can also squash the two commits with the changes (also please use capital letter after colon in the commit message), or leave them as they are and I will squash them before merging.
> 
> I also wonder why there is the dangling commit. Maybe I didn't do it right when merge the upstream.
> 
> It's done now (also merge the fix commit).

Thanks a lot!

**Review by nicdard — APPROVED** [review]

**Pull request merged**
