### PR TITLE
Added example test and instructions on how to include these tests into the personal project

### PR DESCRIPTION
**Pull request by dbernhard-0x7CD**

### CODE REVIEW

**Comment by dbernhard-0x7CD** [comment]
If some author started to make a contribution in the folder his-ethz-username/ we'd have to adjust the Makefile to also look in 03/his-ethz-username.

**Comment by nicdard** [comment]
> If some author started to make a contribution in the folder his-ethz-username/ we'd have to adjust the Makefile to also look in 03/his-ethz-username.

Can you elaborate on this? i don't see any author specific configuration in the guide you posted already in the PR

Thanks!

**Comment by dbernhard-0x7CD** [comment]
This is what we _would_ have to do if each author had its own subfolder (e.ex add compiler-design-eth-tests/03/author1 to the ocamlbuild command)

**Comment by nicdard** [comment]
> This is what we _would_ have to do if each author had its own subfolder (e.ex add compiler-design-eth-tests/03/author1 to the ocamlbuild command)

Oh I see, Sorry but I am travelling already for more than eight hours so I am not really responsive

Can't se use some pattern which includes also subdirectories in the makefile? Like compiler-design-eth-tests/03/**/*?

We can also store it in a variabile, It should be precomputed

I have to try out however not sure if it works, it's some time that I am not using makefiles anymore

**Comment by nicdard** [comment]
Sorry for late answer, I just come back from my trip.

I have checked various options, using either the `_tags` file or `-r` flag. Even directories patterns seems not to  work. I don't really have more time unfortunately, so I would suggest to use this approach as it is working and puts the configuration on the person contributing to the tests, not to the user.

However, just for you to know, this recursive compilation feature comes out of the box with dune, when I use it everything works fine.

Regarding the PR I will add some minor comments, as soon as you address them I am more than happy to merge, so I will start also adding some tests :)

**Comment by nicdard** [comment]
Some general comment:
* Please use imperative form for commit message verbs (if you are curious here is an article about commit messages: https://chris.beams.io/posts/git-commit/)
* Capitalize first letter of commit messages
* I would expect `Dbernhard.ml` not to be capitalized as the other `.ml` files

Apart from this minor stylistic comments, LGTM, thanks a lot!

**Comment by nicdard** [comment]
> Some general comment:
> 
> * Please use imperative form for commit message verbs (if you are curious here is an article about commit messages: https://chris.beams.io/posts/git-commit/)
> * Capitalize first letter of commit messages
> * I would expect `Dbernhard.ml` not to be capitalized as the other `.ml` files
> 
> Apart from this minor stylistic comments, LGTM, thanks a lot!

@dbernhard-0x7CD I can also squash and merge if you are ok with this

**Pull request closed without merging**
